### ISSUE TITLE
ip的检测似乎是不必要的

### ISSUE THREAD

**Issue by Ovler-Young** [Rewrite0/Auto_Bangumi_WebUI#5]
https://github.com/Rewrite0/Auto_Bangumi_WebUI/blob/a1d4ae0c9c4fb213c68bacaa55789a6aeb26f100/src/pages/config/useConfigCheck.ts#L3-L8

https://github.com/Rewrite0/Auto_Bangumi_WebUI/blob/a1d4ae0c9c4fb213c68bacaa55789a6aeb26f100/src/pages/config/useConfigCheck.ts#L25-L27

个人认为这里的ip检查是无必要且错误的，需要删除。

在config中，该字段对应的是`host`，而非ip。host不止有ip这一个选项。

比如在docker的同一个network内，不同容器间可直接通过hostname进行连接，而hostname通不过ip的校验。

**Comment by Rewrite0** [comment]
[v1.1.1](https://github.com/Rewrite0/Auto_Bangumi_WebUI/releases/tag/v1.1.1)
