### ISSUE TITLE
打开后为空白页

### ISSUE THREAD

**Issue by moelody** [Rewrite0/Auto_Bangumi_WebUI#7]
![image](https://user-images.githubusercontent.com/30750380/236095038-b03a1ac0-0cc7-48a9-b955-35c080d99077.png)

控制台报错 index.97c47918.js:1  Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.

**Comment by Rewrite0** [comment]
奇怪的问题, 你可以尝试重建ab容器
